default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("MYTUBE_DATABASE_HOST") { "" } %>

development:
  <<: *default
  database: mytube_development

test:
  <<: *default
  database: mytube_test

production:
  <<: *default
  database: mytube_production
  username: <%= ENV.fetch("MYTUBE_DATABASE_USER") { "mytube" } %>
  password: <%= ENV['MYTUBE_DATABASE_PASSWORD'] %>

staging:
  <<: *default
  database: mytube_staging
  username: <%= ENV.fetch("MYTUBE_DATABASE_USER") { "mytube" } %>
  password: <%= ENV['MYTUBE_DATABASE_PASSWORD'] %>
